### ISSUE TITLE
Meet Mute seems to need to be "initialized"

### ISSUE THREAD

**Issue by panathea** [mattsimonis/meet-mute#10]
- Chrome Version 85.0.4183.121 (Official Build) (64-bit)
- macOS Catalina 10.15.6

This might be a limitation beyond this project's scope, but in order for the extension to work for me, I need to follow this procedure:

1. Open my Meeting
2. Click the Meet Mute extension in the toolbar to mute or unmute myself
3. Now the keyboard shortcut works

If I don't perform step 2 (clicking the extension in the toolbar while the meeting is going,) then the icon remains multicolored and doesn't do anything on click.

**Comment by mattsimonis** [comment]
Hmm, I was not able to reproduce this issue (with the latest changes). Did you set up your keyboard shortcuts under [chrome://extensions/shortcuts](chrome://extensions/shortcuts)? When I set those up there, they work without needing to click the extension at all.

**Comment by panathea** [comment]
Here are my keyboard settings:

![image](https://user-images.githubusercontent.com/5840970/96167416-5d487600-0eed-11eb-8774-ee3d1dd2c0fb.png)

And this is the state of the extension before I click on the icon to activate it during a call:

![image](https://user-images.githubusercontent.com/5840970/96167476-76512700-0eed-11eb-8880-9c8661947e96.png)

**Comment by mattsimonis** [comment]
Perhaps it has something to do with the extension permissions (going to chrome://extensions/ -> Details for Meet Mute)? When you first install, it will ask for these permissions. If they were denied, it might be producing that behavior.

<img width="671" alt="Screen Shot 2020-10-15 at 5 00 18 PM" src="https://user-images.githubusercontent.com/720686/96197903-1d42bc80-0f08-11eb-98ae-e121a7110a27.png">

**Comment by panathea** [comment]
Yes! Thank you for your patience, that permission wasn't granted for some reason. Now that it's enabled, I have no issue.
