### ISSUE TITLE
Does it work on Linux ?

### ISSUE THREAD

**Issue by jefersonlemos** [mattsimonis/meet-mute#5]
I'm currently using Linux Debian 10. with Chrome and Brave and I can't get it working, is it possible for you to help me ?

**Comment by introkun** [comment]
Could be fixed by my PR https://github.com/mattsimonis/meet-mute/pull/8

**Comment by mattsimonis** [comment]
Yes, it should - Brave as well (I just tested it). #8 might fix your issue, which just closed and will be in a new release soon.
