### ISSUE TITLE
Mute/unmute icons differentiated solely by red/green color not accessible to colorblind users

### ISSUE THREAD

**Issue by mcasalaina** [mattsimonis/meet-mute#6]
Thanks for Meet Mute, I use it every day! However as a red/green colorblind person, I have a hard time discerning whether I'm presently muted or not (unless I mouse over it to get the hover text), because the icon is entirely unchanged but for its color when you're muted. As such I'd suggest the icons change to be more like the white/red scheme (with a changing icon) in Google Meet itself. If I have a few minutes I'll make a pull request to try to fix this one myself.

**Comment by introkun** [comment]
@mcasalaina could you please refer to a visual example?

**Comment by mcasalaina** [comment]
The muted state shows the 3 dots in red (see attached); the unmuted state shows the same 3 dots but in green. I'm saying that the unmuted icon and the muted icon should have a visual distinction by something other than just color.
![2020-08-13_10-00-16 (2)](https://user-images.githubusercontent.com/1323111/90164113-d390f680-dd4b-11ea-8fd9-e5798c8dd375.png)
![2020-08-13_10-00-17](https://user-images.githubusercontent.com/1323111/90164135-d986d780-dd4b-11ea-9580-ef632c9d51bd.png)

**Comment by mcasalaina** [comment]
I went and fixed the icons in my branch and made a pull request for it. Hopefully it'll be accepted. :)

**Comment by mattsimonis** [comment]
Fixed by #9. Closing.
