### ISSUE TITLE
Clicking the mute icon changes color but does not affect Meet

### ISSUE THREAD

**Issue by kerridge** [mattsimonis/meet-mute#7]
- Has not worked for me once
- Tried changing site permissions, restarting Chrome, restarting my PC, adding a keybind - nothing worked
- Latest version of Chrome
- Company managed G-Suite account
- No other Meet or Muting extensions enabled

**Comment by introkun** [comment]
Could be fixed by my PR https://github.com/mattsimonis/meet-mute/pull/8

**Comment by mattsimonis** [comment]
#8 might fix this because of language. I've tested on the latest Chrome and it works for me. This should be released some time soon. If you still have the issue after that release, feel free to open an issue.
